#端口
server:
  port: 9000
# 数据库连接信息
spring:
  datasource:
           url: jdbc:mysql://sc.vip.com:3306/simons?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
           username: root
           password: root
           driver-class-name: com.mysql.jdbc.Driver
  application:
    name: ticket-consumer-ribbon
# mybatis扫描信息
mybatis:
  typeAliasesPackage: com.simons.cn.bean       #实体对象所以在包
  mapper-locations: classpath:mapper/*.xml       #xml文件位置

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
  instance:
     prefer-ip-address: true

user-provider:    #这里是用户微服务的节点名称
  ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

