#端口
server:
  port: 7000

# 数据库连接信息
spring:
  datasource:
           url: jdbc:mysql://sc.vip.com:3306/simons?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
           username: root
           password: root
           driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-provider-sleuth


#日志信息
logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: debug

# mybatis扫描信息
mybatis:
  typeAliasesPackage: com.simons.cn.bean       #实体对象所以在包
  mapper-locations: classpath:mapper/*.xml       #xml文件位置


