#端口
server:
  port: 10010
#注册到Eureka中的实例名
spring:
  application:
    name: zuul-gataway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
  instance:
     prefer-ip-address: true
#加上超时参数
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    user-provider: /user/**
  PreRequestZuulFilter:      ##禁用SpringCloud为Zuul开启的一些过滤器，这里以禁用我自定义的PreRequestZuulFilter过滤器为例
    pre:
      disable: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

